version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [backend]

  backend:
    container_name: api
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"        # FastAPI docs at /docs
    networks: [backend, frontend]

  frontend:
    container_name: streamlit
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file: .env
    depends_on: [backend]
    ports:
      - "8501:8501"
    networks: [backend, frontend]

volumes:
  db_data:

networks:
  backend:
  frontend:
